# Generated by Django 6.0 on 2026-02-12 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 15, 56, 17, 216634, tzinfo=datetime.timezone.utc)),
        ),
    ]
