# Generated by Django 6.0 on 2026-02-12 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 15, 57, 18, 792033, tzinfo=datetime.timezone.utc)),
        ),
    ]
