# Generated by Django 5.2.17 on 2026-08-16 07:09

import user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_usersession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='expiry_date',
            field=models.DateTimeField(default=user_auth.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(default=user_auth.models.generate_uuid, max_length=128, unique=True),
        ),
    ]
