# Generated by Django 5.2.17 on 2026-08-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_created_at'),
        ('user_auth', '0004_user_is_active_user_is_staff_alter_user_created_at_and_more'),
        ('user_auth', '0005_alter_usersession_expiry_date_and_more'),
    ]

    operations = [
    ]
