# Generated by Django 5.2.17 on 2026-09-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_user_phone_number_user_role_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={},
        ),
    ]
