# Generated by Django 5.2.17 on 2026-09-08 08:28

import django.db.models.deletion
import django.utils.timezone
import master.models.models_contact_master
import user_auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_userrole_options_alter_usersession_options'),
    ]

    operations = [
        # created_by_id/updated_by_id already exist physically on the `roles`
        # table (it predates a proper migration history); only teach the
        # migration state about them, don't try to add the columns again.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userrole',
                    name='created_by',
                    field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userrole',
                    name='updated_by',
                    field=models.ForeignKey(db_column='updated_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
                ),
            ],
            database_operations=[],
        ),
        # user_id already exists physically on user_session for the same reason.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='usersession',
                    name='user',
                    field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='userrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(default=user_auth.models.generate_uuid, max_length=64, unique=True),
        ),
    ]
