# Generated by Django 5.2.17 on 2026-09-08 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('ledger_name', models.CharField(max_length=255)),
                ('ledger_code', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('particulars', models.TextField(blank=True, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transaction_type', models.CharField(max_length=50)),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loan_ledger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenure_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value_date_ad', models.DateField(blank=True, null=True)),
                ('emi_date_ad', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loan_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRequestHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('DISBURSED', 'Disbursed')], max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'loan_request_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestWorkflow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_void', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_workflow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleTransactionLimit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_void', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_transaction_limit',
                'managed': False,
            },
        ),
    ]
