# Generated by Django 5.2.17 on 2026-09-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanledger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanrequesthistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requestworkflow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roletransactionlimit',
            options={},
        ),
    ]
