# Generated by Django 5.2.17 on 2026-09-08 08:28

import django.db.models.deletion
import master.models.models_contact_master
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanledger_options_alter_loanrequest_options_and_more'),
        ('master', '0005_clientmaster_citizenship_issued_district_and_more'),
        ('tools', '0004_clienttypegender_created_by_documenttype_created_by_and_more'),
        ('user_auth', '0009_userrole_created_by_userrole_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanledger',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='master.clientmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanledger',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanledger',
            name='loan_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='loan.loanrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='master.clientmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_loan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='follower_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='user_auth.userrole'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tools.loanpurpose'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='tools.loantype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='payment_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tools.loanpaymentscheme'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_loan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequesthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequesthistory',
            name='from_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user_auth.userrole'),
        ),
        migrations.AddField(
            model_name='loanrequesthistory',
            name='loan_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='loan.loanrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequesthistory',
            name='to_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user_auth.userrole'),
        ),
        migrations.AddField(
            model_name='loanrequesthistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestworkflow',
            name='follower_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_auth.userrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestworkflow',
            name='initiator_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_auth.userrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roletransactionlimit',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roletransactionlimit',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user_auth.userrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roletransactionlimit',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanledger',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='loanrequesthistory',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='requestworkflow',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='roletransactionlimit',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
    ]
