# Generated by Django 6.0 on 2026-02-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='de7ffc9e5c6b42258bda6337aafd4bd5', max_length=32)),
                ('client_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth_ad', models.DateField(blank=True, null=True)),
                ('date_of_birth_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('grandfather_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_issued_date_ad', models.DateField(blank=True, null=True)),
                ('identity_issued_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('citizenship_issued_date_ad', models.DateField(blank=True, null=True)),
                ('citizenship_issued_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_ward_number', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_street', models.CharField(blank=True, max_length=255, null=True)),
                ('temp_ward_number', models.CharField(blank=True, max_length=10, null=True)),
                ('temp_street', models.CharField(blank=True, max_length=255, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nominee_relation', models.IntegerField()),
                ('nominee_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_date_of_birth_ad', models.DateField(blank=True, null=True)),
                ('nominee_date_of_birth_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_status', models.IntegerField()),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_authority', models.IntegerField()),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='de7ffc9e5c6b42258bda6337aafd4bd5', max_length=32)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=30)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship_number', models.CharField(max_length=100)),
                ('citizenship_issued_date_ad', models.DateField()),
                ('citizenship_issued_date_bs', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'global_client_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalDistrict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='de7ffc9e5c6b42258bda6337aafd4bd5', max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'global_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalProvince',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='de7ffc9e5c6b42258bda6337aafd4bd5', max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'global_province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalVdcMunicipality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='de7ffc9e5c6b42258bda6337aafd4bd5', max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.globaldistrict')),
            ],
            options={
                'db_table': 'global_vdc_municipality',
            },
        ),
    ]
