# Generated by Django 5.2.17 on 2026-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalprovince',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='globalvdcmunicipality',
            name='reference_id',
            field=models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32),
        ),
    ]
