# Generated by Django 5.2.17 on 2026-09-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_globalprovince_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='globaldistrict',
            options={},
        ),
        migrations.AlterModelOptions(
            name='globalprovince',
            options={},
        ),
        migrations.AlterField(
            model_name='globalvdcmunicipality',
            name='reference_id',
            field=models.CharField(default='d26d9b31d1ac4fe88ae647eca21e7173', max_length=32),
        ),
    ]
