# Generated by Django 5.2.17 on 2026-09-08 08:28

import django.db.models.deletion
import master.models.models_contact_master
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_create_missing_tables'),
        ('tools', '0004_clienttypegender_created_by_documenttype_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmaster',
            name='citizenship_issued_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globaldistrict'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='global_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.contactmaster'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='identity_issued_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globaldistrict'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='permanent_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globaldistrict'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='permanent_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globalvdcmunicipality'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='permanent_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globalprovince'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='temp_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globaldistrict'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='temp_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globalvdcmunicipality'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='temp_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globalprovince'),
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='citizenship_issued_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globaldistrict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='permanent_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globaldistrict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='permanent_province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globalprovince'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='permanent_vdc_municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.globalvdcmunicipality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='permanent_ward_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # The `province_id` column already exists physically on global_district
        # (this table predates a proper migration history); only teach the
        # migration state about it, don't try to add the column again.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='globaldistrict',
                    name='province',
                    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='master.globalprovince'),
                    preserve_default=False,
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='created_by', null=True),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tools.clienttypegender'),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='legal_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tools.legalstatus'),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='nominee_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tools.nomineerelation'),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='registration_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tools.registrationauthority'),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='updated_by', null=True),
        ),
        migrations.AlterField(
            model_name='contactmaster',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='globaldistrict',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='globalprovince',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='globalvdcmunicipality',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
    ]
