# Generated by Django 5.2.17 on 2026-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_clientmaster_citizenship_issued_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
