# Generated by Django 6.0 on 2026-02-12 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadQuotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='0ee342ad7f534e6690ab99cc71b13b6e', max_length=32)),
                ('quotation_number', models.IntegerField(blank=True, null=True)),
                ('cic_status', models.CharField(blank=True, max_length=255, null=True)),
                ('next_follow_up_days', models.IntegerField(blank=True, null=True)),
                ('follow_up_1_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('follow_up_2_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('follow_up_3_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('follow_up_4_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('is_documents_submitted', models.BooleanField(default=False)),
                ('is_document_approved', models.BooleanField(default=False)),
                ('is_document_rejected', models.BooleanField(default=False)),
                ('approval_remarks', models.TextField()),
                ('reject_remarks', models.TextField()),
            ],
            options={
                'db_table': 'lead_quotation_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadQuotationDocuments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='0ee342ad7f534e6690ab99cc71b13b6e', max_length=32)),
                ('file_name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lead_quotation_documents',
                'managed': False,
            },
        ),
    ]
