# Generated by Django 5.2.17 on 2026-09-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadquotation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leadquotationdocuments',
            options={},
        ),
    ]
