# Generated by Django 5.2.17 on 2026-09-08 08:28

import django.db.models.deletion
import master.models.models_contact_master
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_leadquotation_options_and_more'),
        ('master', '0005_clientmaster_citizenship_issued_district_and_more'),
        ('tools', '0004_clienttypegender_created_by_documenttype_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquotation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.contactmaster'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='loan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tools.loantype'),
        ),
        migrations.AddField(
            model_name='leadquotation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tools.leadsource'),
        ),
        migrations.AddField(
            model_name='leadquotationdocuments',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.leadquotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadquotation',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='leadquotationdocuments',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
    ]
