# Generated by Django 5.2.17 on 2026-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_leadquotation_contact_leadquotation_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadquotationdocuments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leadquotationdocuments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
