# Generated by Django 5.2.17 on 2026-09-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_leadquotationdocuments_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadquotation',
            name='quotation_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        # A plain SELECT MAX(quotation_number) + 1 followed by an INSERT is a
        # race condition under concurrent requests (two requests can read the
        # same max and both insert the same number). A Postgres sequence's
        # nextval() is atomic regardless of concurrency, so use one instead.
        # Start it past whatever quotation_number data already exists.
        migrations.RunSQL(
            sql="""
                DO $$
                DECLARE
                    next_val integer;
                BEGIN
                    SELECT COALESCE(MAX(quotation_number), 1) + 1 INTO next_val
                    FROM lead_quotation_registration;
                    EXECUTE format(
                        'CREATE SEQUENCE IF NOT EXISTS lead_quotation_number_seq START WITH %s',
                        next_val
                    );
                END $$;
            """,
            reverse_sql="DROP SEQUENCE IF EXISTS lead_quotation_number_seq;",
        ),
    ]
