# Generated by Django 5.2.17 on 2026-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'legal_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanPaymentScheme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('name_in_nepali', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('remarks_in_nepali', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loan_payment_scheme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanPurpose',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'loan_purpose_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NomineeRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'nominee_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationAuthority',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='98117df13cb5412eb63676bd7680f33c', max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'registration_authority',
                'managed': False,
            },
        ),
    ]
