# Generated by Django 5.2.17 on 2026-09-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_legalstatus_loanpaymentscheme_loanpurpose_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttypegender',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='legalstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanpaymentscheme',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanpurpose',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loantype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nomineerelation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrationauthority',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salutation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemday',
            options={'ordering': ['-business_date_ad']},
        ),
    ]
