# Generated by Django 5.2.17 on 2026-09-08 08:28

import django.db.models.deletion
import master.models.models_contact_master
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_clienttypegender_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttypegender',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanpaymentscheme',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanpaymentscheme',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanpurpose',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loantype',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_types_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nationality',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salutation',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienttypegender',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='legalstatus',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='loanpaymentscheme',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='loanpurpose',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='nomineerelation',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationauthority',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='salutation',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='systemday',
            name='reference_id',
            field=models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True),
        ),
    ]
