# Generated by Django 5.2.17 on 2026-09-08 10:00

import django.db.models.deletion
import master.models.models_contact_master
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_clienttypegender_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCollateralType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default=master.models.models_contact_master.generate_uuid, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_collateral_type',
            },
        ),
    ]
