-- Manually constructed SQL for LoanRequest model
BEGIN;
CREATE TABLE "loan_request" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "client_id" bigint NOT NULL REFERENCES "client_master" ("id") DEFERRABLE INITIALLY DEFERRED,
    "loan_type_id" bigint NOT NULL REFERENCES "loan_type" ("id") DEFERRABLE INITIALLY DEFERRED,
    "amount" numeric(15, 2) NOT NULL,
    "tenure_months" integer NOT NULL,
    "purpose" text NOT NULL,
    "interest_rate" numeric(5, 2) NOT NULL,
    "value_date" date NULL,
    "emi_date" date NULL,
    "status" varchar(50) NOT NULL,
    "remarks" text NULL,
    "payment_scheme" varchar(100) NULL,
    "is_void" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "created_by" integer NULL REFERENCES "user_auth_newuser" ("id") DEFERRABLE INITIALLY DEFERRED,
    "updated_by" integer NULL REFERENCES "user_auth_newuser" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "loan_ledger" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "loan_request_id" bigint NOT NULL REFERENCES "loan_request" ("id") DEFERRABLE INITIALLY DEFERRED,
    "client_id" bigint NOT NULL REFERENCES "client_master" ("id") DEFERRABLE INITIALLY DEFERRED,
    "ledger_name" varchar(255) NOT NULL,
    "ledger_code" varchar(100) NOT NULL,
    "transaction_date" date NOT NULL,
    "particulars" text NULL,
    "debit_amount" numeric(15, 2) NOT NULL DEFAULT 0.00,
    "credit_amount" numeric(15, 2) NOT NULL DEFAULT 0.00,
    "balance_amount" numeric(15, 2) NOT NULL DEFAULT 0.00,
    "transaction_type" varchar(50) NOT NULL,
    "is_void" boolean NOT NULL DEFAULT False,
    "created_at" timestamp with time zone NOT NULL,
    "created_by" integer NULL REFERENCES "user_auth_newuser" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "loan_ledger_loan_request_id_idx" ON "loan_ledger" ("loan_request_id");
CREATE INDEX "loan_ledger_client_id_idx" ON "loan_ledger" ("client_id");
CREATE INDEX "loan_ledger_ledger_code_idx" ON "loan_ledger" ("ledger_code");
CREATE INDEX "loan_ledger_transaction_date_idx" ON "loan_ledger" ("transaction_date");
CREATE INDEX "loan_request_client_id_idx" ON "loan_request" ("client_id");
CREATE INDEX "loan_request_loan_type_id_idx" ON "loan_request" ("loan_type_id");
CREATE INDEX "loan_request_created_by_idx" ON "loan_request" ("created_by");
CREATE INDEX "loan_request_updated_by_idx" ON "loan_request" ("updated_by");
COMMIT;
